# Generated by Django 3.1.4 on 2020-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40, verbose_name='Displayed name of temperature sensor')),
                ('short_name', models.CharField(max_length=40, verbose_name='Short hand for temperature sensor')),
                ('address', models.CharField(max_length=30, verbose_name='1-wire address of temperature sensor.')),
                ('has_power', models.BooleanField(default=False, verbose_name='Is power supplied via the power pin?')),
                ('last_update', models.DateTimeField(default=None, verbose_name='Timestamp of the last value')),
                ('value', models.FloatField(default=-200, verbose_name='The current (last) temperature in degrees C.')),
            ],
        ),
    ]
