# Generated by Django 4.1.5 on 2023-01-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("temperature_sensors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureSensorGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, verbose_name="Temperature sensor group"
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Group display order")),
            ],
        ),
        migrations.AddField(
            model_name="temperaturesensor",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="temperature_sensors.temperaturesensorgroup",
            ),
        ),
    ]
