# Generated by Django 3.1.4 on 2020-12-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Temperature in degrees C.')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp of temperature value')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='temperature_sensors.temperaturesensor')),
            ],
        ),
    ]
