# Generated by Django 4.1.5 on 2023-01-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("temperature_sensors", "0002_temperaturesensorgroup_temperaturesensor_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperaturesensor",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="temperature_sensors.temperaturesensorgroup",
            ),
        ),
    ]
