# Generated by Django 3.1.4 on 2020-12-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_sensors', '0002_temperatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='address',
            field=models.CharField(max_length=30, unique=True, verbose_name='1-wire address of temperature sensor.'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='last_update',
            field=models.DateTimeField(default=None, null=True, verbose_name='Timestamp of the last value'),
        ),
    ]
