# Generated by Django 3.1.4 on 2020-12-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name of camera')),
                ('image_address', models.CharField(max_length=30, unique=True, verbose_name='Address of image to collect')),
                ('last_update', models.DateTimeField(default=None, null=True, verbose_name='Timestamp of the last image')),
                ('last_image', models.CharField(max_length=200, verbose_name='(Partial) path to current image.')),
            ],
        ),
        migrations.CreateModel(
            name='CameraImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=None, null=True, verbose_name='Timestamp of the image')),
                ('image_path', models.CharField(max_length=200, verbose_name='(Partial) path to image')),
                ('camera_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.cameras')),
            ],
        ),
    ]
