# Generated by Django 3.1.4 on 2020-12-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='CameraImages',
            new_name='CameraImage',
        ),
    ]
