# Generated by Django 3.1.4 on 2020-12-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20201226_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(max_length=40, null=True, verbose_name='Password for camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.CharField(max_length=40, null=True, verbose_name='User name for camera'),
        ),
    ]
