# Generated by Django 3.1.4 on 2020-12-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20201228_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image_address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Address of image to collect'),
        ),
    ]
